LibraryService.Web/Models/BookCategoryViewModel.cs
using LibraryServiceReference;

namespace LibraryService.Web.Models
{
    public class BookCategoryViewModel
    {
        public Book[] Books { get; set; }
        public SearchType SearchType { get; set; }
        public string SearchString { get; set; }
    }
}

LibraryService.Web/Models/ErrorViewModel.cs
namespace LibraryService.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

LibraryService.Web/Models/SearchType.cs
using System.ComponentModel.DataAnnotations;

namespace LibraryService.Web.Models
{
    public enum SearchType
    {
        [Display(Name = "Заголовок")]
        Title,
        [Display(Name = "Автор")]
        Author,
        [Display(Name = "Категория")]
        Category
    }
}

LibraryService.Web/Controllers/LibraryController.cs
using LibraryService.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using LibraryServiceReference;

namespace LibraryService.Web.Controllers
{
    public class LibraryController : Controller
    {
        private readonly ILogger<LibraryController> _logger;
        private readonly LibraryWebServiceSoapClient _libraryWebServiceSoapClient;

        public LibraryController(ILogger<LibraryController> logger, LibraryWebServiceSoapClient libraryWebServiceSoapClient)
        {
            _logger = logger;
            _libraryWebServiceSoapClient = libraryWebServiceSoapClient;
        }

        public IActionResult Index(SearchType searchType, string searchString)
        {
            var bookCategoryViewModel = new BookCategoryViewModel
            {
                Books = new Book[] {}
            };

            if (!string.IsNullOrEmpty(searchString) && searchString.Length > 3)
            {
                bookCategoryViewModel.Books = searchType switch
                {
                    SearchType.Title => _libraryWebServiceSoapClient.GetBooksByTitle(searchString),
                    SearchType.Category => _libraryWebServiceSoapClient.GetBooksByCategory(searchString),
                    SearchType.Author => _libraryWebServiceSoapClient.GetBooksByAuthor(searchString),
                    _ => bookCategoryViewModel.Books
                };
            }

            return View(bookCategoryViewModel);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

LibraryService.Web/Views/Library/Index.cshtml
@model BookCategoryViewModel

@{
    ViewData["Title"] = "Library Page";
}

<form asp-controller="Library" asp-action="Index">
    <p>
        <select asp-for="SearchType" asp-items="Html.GetEnumSelectList<SearchType>()">
        </select>
        
        <input type="text" name="SearchString"/>
        <input type="submit" value="Поиск"/>
    </p>
</form>

<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Books[0].Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Books[0].Category)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Books[0].Authors)
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model.Books)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Authors)
            </td>
        </tr>
    }
    </tbody>
</table>

LibraryService.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LibraryService.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LibraryService.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Library" asp-action="Index">LibraryService.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Library" asp-action="Index">Library</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - LibraryService.Web - <a asp-area="" asp-controller="Library">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>